version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: skroutz_scraper
      POSTGRES_USER: skroutz_user
      POSTGRES_PASSWORD: skroutz_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - elastic

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.3.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:9.3.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - CSP_STRICT=false
      - SERVER_PUBLICBASEURL=http://localhost:5601
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - elastic

volumes:
  postgres_data:
  elasticsearch_data:
    driver: local

networks:
  elastic: