
spring:
  application:
    name: skroutz-web-scraper
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/skroutz_scraper
    username: skroutz_user
    password: skroutz_password
    driver-class-name: org.postgresql.Driver
  
  # JPA/Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  
  # Flyway Configuration
  flyway:
    schemas: scraper_schema

# Scraper Configuration
scraper:
  headless: false
  timeout: 100
  chromeUserDataDir: C:\\Users\\Christos\\AppData\\Local\\Google\\Chrome\\User Data\\Default
  base-url: https://www.skroutz.gr

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
server:
  port: 8082